const data = {
  products: [
    {
      name: 'Basic Shirt ',
      slug: 'basic-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt ',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 50,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt ',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants ',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Levis',
      rating: 3.1,
      numReviews: 13,
      countInStock: 20,
      description: 'Confy pants for everyday',
    },
    {
      name: 'Fit Pants ',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 49,
      brand: 'Zara',
      rating: 2.5,
      numReviews: 4,
      countInStock: 17,
      description: 'Confy pants for everyday',
    },
    {
      name: 'Classis Pants ',
      slug: 'classis-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 30,
      brand: 'H&M',
      rating: 4.3,
      numReviews: 7,
      countInStock: 12,
      description: 'Confy pants for everyday',
    },
  ],
};

export default data;
